apiVersion: v1
kind: Service
metadata:
  name: sample-python-project
  namespace: python-deploy
  labels:
    app: sample-python-project
spec:
  type: ClusterIP
  selector:
    app: sample-python-project
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
